name: Discord Notification

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    name: Send Discord Notification
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set permissions for notification script
        run: chmod +x .github/workflows/send.sh

      - name: Success Notification
        if: ${{ success() }}
        run: ./.github/workflows/send.sh success ${{ secrets.WEBHOOK_URL }}
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      - name: Failure Notification
        if: ${{ failure() }}
        run: ./.github/workflows/send.sh failure ${{ secrets.WEBHOOK_URL }}
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
