name: Node.js CI

on:
  push:
    branches: [ "main", "feature/*", "maintainence/*"]
  pull_request:
    branches: [ "main", "feature/*", "maintainence/*"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
  notify:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    name: Send Discord Notification
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set permissions for notification script
        run: chmod +x .github/workflows/send.sh

      - name: Send Notification
        run: |
          if [ "${{ needs.build.result }}" == "success" ]; then
            ./.github/workflows/send.sh success $WEBHOOK_URL
          else
            ./.github/workflows/send.sh failure $WEBHOOK_URL
          fi
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
